{{- if .Values.rbac.create -}}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "steadybit-outpost.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "steadybit-outpost.commonLabels" . | nindent 4 }}
  {{- range $key, $value := .Values.outpost.extraLabels }}
    {{ $key }}: {{ $value }}
  {{- end }}
subjects:
  - kind: ServiceAccount
    name: {{ template "steadybit-outpost.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ template "steadybit-outpost.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
  {{- end -}}