apiVersion: v1
kind: Secret
metadata:
  name: {{ template "steadybit-outpost.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "steadybit-outpost.commonLabels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.outpost.key }}
  key: {{ .Values.outpost.key | b64enc | quote }}
  {{- end }}
  {{- if .Values.outpost.auth.oauth2.clientSecret.value }}
  oauth2ClientSecret: {{ .Values.outpost.auth.oauth2.clientSecret.value | b64enc | quote }}
  {{- end }}
  {{- if .Values.outpost.auth.oauth2.tls.clientCertificate.key.password.value }}
  oauth2ClientKeyPassword: {{ .Values.outpost.auth.oauth2.tls.clientCertificate.key.password.value | b64enc | quote }}
  {{- end }}
  {{- if .Values.outpost.extensions.tls.clientCertificate.key.password.value }}
  extensionsClientKeyPassword: {{ .Values.outpost.extensions.tls.clientCertificate.key.password.value | b64enc | quote }}
  {{- end }}
