{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "steadybit-outpost.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  {{- if .Values.serviceAccount.eksRoleArn }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.eksRoleArn | quote }}
  {{- end }}
  labels:
    {{- include "steadybit-outpost.commonLabels" . | nindent 4 }}
  {{- range $key, $value := .Values.outpost.extraLabels }}
    {{ $key }}: {{ $value }}
  {{- end }}
automountServiceAccountToken: true
{{- end }}
