apiVersion: v2
name: steadybit-platform
description: steadybit Platform Helm chart for Kubernetes.
version: 0.4.3
appVersion: latest
home: https://www.steadybit.com/
icon: https://steadybit-website-assets.s3.amazonaws.com/logo-symbol-transparent.png
maintainers:
  - email: dennis.schulte@steadybit.com
    name: denschu
sources:
  - https://github.com/steadybit/helm-charts
annotations:
  artifacthub.io/images: |
    - name: logo
      image: https://steadybit-website-assets.s3.amazonaws.com/logo-symbol-transparent.png
  artifacthub.io/links: |-
    - name: steadybit website
      url: https://www.steadybit.com
    - name: steadybit Kubernetes Helm charts
      url: https://github.com/steadybit/helm-charts
dependencies:
  - name: postgresql
    version: 11.1.15
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
