apiVersion: v2
name: steadybit-extension-aws
description: Steadybit AWS extension Helm chart for Kubernetes.
version: 1.7.0
appVersion: latest
home: https://www.steadybit.com/
icon: https://steadybit-website-assets.s3.amazonaws.com/logo-symbol-transparent.png
maintainers:
  - email: ben.blackmore@steadybit.com
    name: bripkens
sources:
  - https://github.com/steadybit/helm-charts
annotations:
  artifacthub.io/images: |
    - name: logo
      image: https://steadybit-website-assets.s3.amazonaws.com/logo-symbol-transparent.png
  artifacthub.io/links: |-
    - name: steadybit website
      url: https://www.steadybit.com
    - name: steadybit Kubernetes Helm charts
      url: https://github.com/steadybit/helm-charts
