{{- if and (.Values.kong.headerKey) (.Values.kong.headerValue) -}}
apiVersion: v1
kind: Secret
metadata:
  name: steadybit-extension-kong-header
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  key: {{ .Values.kong.headerKey | b64enc | quote }}
  value: {{ .Values.kong.headerValue | b64enc | quote }}
{{- end }}