apiVersion: v1
kind: Service
metadata:
  name: steadybit-extension-kong
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app.kubernetes.io/name: steadybit-extension-kong
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
