apiVersion: v2
name: steadybit-extension-kubernetes
description: Steadybit Kubernetes extension Helm chart for Kubernetes.
version: 1.4.6
appVersion: latest
home: https://www.steadybit.com/
icon: https://steadybit-website-assets.s3.amazonaws.com/logo-symbol-transparent.png
maintainers:
  - email: ben.blackmore@steadybit.com
    name: bripkens
  - email: daniel.reuter@steadybit.com
    name: reuda
  - email: ansgar.schulte@steadybit.com
    name: ansgarschulte
sources:
  - https://github.com/steadybit/helm-charts
annotations:
  artifacthub.io/images: |
    - name: logo
      image: https://steadybit-website-assets.s3.amazonaws.com/logo-symbol-transparent.png
  artifacthub.io/links: |-
    - name: steadybit website
      url: https://www.steadybit.com
    - name: steadybit Kubernetes Helm charts
      url: https://github.com/steadybit/helm-charts
dependencies:
  - name: extensionlib
    version: ~1.1.0
    repository: file://../extensionlib
