{{- if .Values.rbac.create -}}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "steadybit-agent.fullname" . }}
  labels:
    {{- include "steadybit-agent.commonLabels" . | nindent 4 }}
  {{- range $key, $value := .Values.agent.extraLabels }}
    {{ $key }}: {{ $value }}
  {{- end }}
rules:
  - apiGroups: [ "batch" ]
    resources:
      - "jobs"
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "extensions" ]
    resources:
      - "deployments"
      - "replicasets"
      - "ingresses"
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "apps" ]
    resources:
      - "deployments"
      - "replicasets"
      - "daemonsets"
      - "statefulsets"
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "autoscaling" ]
    resources:
      - "horizontalpodautoscalers"
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "networking.k8s.io" ]
    resources:
      - "ingresses"
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "" ]
    resources:
      - "events"
      - "namespaces"
      - "services"
      - "endpoints"
      - "nodes"
      - "pods"
      - "pods/log"
      - "replicationcontrollers"
    verbs: [ "get", "list", "watch" ]
  {{- if not .Values.rbac.readonly }}
  - apiGroups: [ "" ]
    resources:
      - "pods"
    verbs: [ "delete" ]
  {{- end }}
  {{- if or .Values.agent.openshift (.Capabilities.APIVersions.Has "apps.openshift.io/v1") }}
  - apiGroups: ["security.openshift.io"]
    resourceNames: ["privileged"]
    resources: ["securitycontextconstraints"]
    verbs: ["use"]
  {{- end }}
  {{- if .Values.podSecurityPolicy.enable}}
  - apiGroups: [ "policy" ]
    resources: [ "podsecuritypolicies" ]
    verbs: [ "use" ]
    resourceNames:
      - {{ template "steadybit-agent.podSecurityPolicyName" . }}
  {{- end -}}
  {{- end -}}