{{- if .Values.rbac.create -}}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "steadybit-agent.fullname" . }}
  labels:
  {{- include "steadybit-agent.commonLabels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ template "steadybit-agent.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ template "steadybit-agent.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
  {{- end -}}