{{- if .Values.agent.key -}}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ template "steadybit-agent.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "steadybit-agent.commonLabels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
  {{- include "steadybit-agent.selectorLabels" . | nindent 6 }}
  updateStrategy:
    type: {{ .Values.updateStrategy.type }}
    {{- if eq .Values.updateStrategy.type "RollingUpdate" }}
    rollingUpdate:
      maxUnavailable: {{ .Values.updateStrategy.rollingUpdate.maxUnavailable }}
  {{- end }}
  template:
    metadata:
      labels:
        com.steadybit.agent: "true"
    {{- include "steadybit-agent.commonLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ template "steadybit-agent.serviceAccountName" . }}
      hostIPC: true
      hostNetwork: true
      hostPID: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: steadybit-agent
          image: "{{ .Values.image.name }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: STEADYBIT_AGENT_REGISTER_URL
              value: {{ .Values.agent.registerUrl | quote }}
            - name: STEADYBIT_AGENT_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ template "steadybit-agent.fullname" . }}
                  key: key
          securityContext:
            privileged: true
          volumeMounts:
            - name: steadybit-agent-state
              mountPath: /var/lib/steadybit-agent
            - name: container-sock
              mountPath: {{ include "container-sock" . }}
            - name: cgroup-root
              mountPath: /sys/fs/cgroup
              readOnly: true
            {{- if include "runc-root" . }}
            - name: runc-root
              mountPath: {{ include "runc-root" . }}
            {{- end }}
            {{- if .Values.agent.additionalVolumes }}
            {{- range $index,$backend := .Values.agent.additionalVolumes }}
            {{ $volumeIndex :=add $index 2 -}}
            - name: {{ $backend.name }}
              mountPath: {{ $backend.mountPath }}
            {{- end }}
      {{- end }}
      imagePullSecrets:
        - name: docker-steadybit-io
      volumes:
        - name: steadybit-agent-state
          hostPath:
            path: /var/lib/steadybit-agent
        - name: container-sock
          hostPath:
            path: {{ include "container-sock" . }}
        - name: cgroup-root
          hostPath:
            path: /sys/fs/cgroup
        {{- if include "runc-root" . }}
        - name: runc-root
          hostPath:
            path: {{ include "runc-root" . }}
        {{- end }}
        {{- if .Values.agent.additionalVolumes }}
        {{- range $index,$backend := .Values.agent.additionalVolumes }}
        {{ $volumeIndex :=add $index 2 -}}
        - name: {{ $backend.name }}
          hostPath:
            path: {{ $backend.hostPath }}
        {{- end }}
  {{- end }}
  {{- end -}}