{{- if .Values.agent.key -}}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ template "steadybit-agent.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "steadybit-agent.commonLabels" . | nindent 4 }}
    {{- range $key, $value := .Values.agent.extraLabels }}
    {{ $key }}: {{ $value }}
  {{- end }}
spec:
  selector:
    matchLabels:
  {{- include "steadybit-agent.selectorLabels" . | nindent 6 }}
  updateStrategy:
    type: {{ .Values.updateStrategy.type }}
    {{- if eq .Values.updateStrategy.type "RollingUpdate" }}
    rollingUpdate:
      maxUnavailable: {{ .Values.updateStrategy.rollingUpdate.maxUnavailable }}
  {{- end }}
  template:
    metadata:
      labels:
        {{- include "steadybit-agent.commonLabels" . | nindent 8 }}
        {{- range $key, $value := .Values.agent.extraLabels }}
        {{ $key }}: {{ $value }}
      {{- end }}
      {{- with .Values.podAnnotations }}
      annotations:
      {{- toYaml . | nindent 8 }}
    {{- end }}
    spec:
      serviceAccountName: {{ template "steadybit-agent.serviceAccountName" . }}
      hostIPC: true
      hostNetwork: true
      hostPID: true
      dnsPolicy: ClusterFirstWithHostNet
      {{- if .Values.priorityClassName.use }}
      priorityClassName: {{ .Values.priorityClassName.name }}
      {{- end }}
      containers:
        - name: steadybit-agent
          image: "{{ .Values.image.name }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            requests:
              memory: {{ .Values.resources.requests.memory }}
              cpu: {{ .Values.resources.requests.cpu }}
            limits:
              memory: {{ .Values.resources.limits.memory }}
              cpu: {{ .Values.resources.limits.cpu }}
          {{ if eq .Values.agent.remoteDebug true }}
          command: ["./bin/run.sh", "debug"]
          ports:
            - containerPort: 5005
              protocol: TCP
          {{ end }}
          env:
            - name: STEADYBIT_AGENT_REGISTER_URL
              value: {{ .Values.agent.registerUrl | quote }}
            - name: STEADYBIT_AGENT_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ template "steadybit-agent.fullname" . }}
                  key: key
            - name: STEADYBIT_KUBERNETES_CLUSTER_NAME
              value: {{ .Values.cluster.name | quote }}
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: STEADYBIT_AGENT_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: STEADYBIT_AGENT_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: STEADYBIT_AGENT_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
{{- with .Values.agent.env }}
{{ toYaml . | indent 12 }}
{{- end }}
          securityContext:
            privileged: true
          volumeMounts:
            - name: steadybit-agent-state
              mountPath: /var/lib/steadybit-agent
            - name: container-sock
              mountPath: {{ include "container-sock" . }}
            - name: cgroup-root
              mountPath: /sys/fs/cgroup
            - name: sys
              mountPath: /sys
            {{- if include "runc-root" . }}
            - name: runc-root
              mountPath: {{ include "runc-root" . }}
            {{- end }}
            {{- if or .Values.agent.openshift (.Capabilities.APIVersions.Has "apps.openshift.io/v1") }}
            - name: run-containers
              mountPath: /run/containers
            - name: var-lib-containers
              mountPath: /var/lib/containers
            - name: var-run
              mountPath: /var/run
            {{- end }}
            {{- if eq (include "steadybit-agent.hasVolumeExtraCerts" . ) "true" }}
            - name: extra-certs
              mountPath: /opt/steadybit/agent/etc/extra-certs
            {{- end }}
{{- with .Values.agent.extraVolumeMounts  }}
{{ toYaml . | indent 12 }}
{{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      imagePullSecrets:
        - name: docker-steadybit-io
      volumes:
        - name: steadybit-agent-state
          hostPath:
            path: /var/lib/steadybit-agent
        - name: container-sock
          hostPath:
            path: {{ include "container-sock-host-path" . }}
        - name: cgroup-root
          hostPath:
            path: /sys/fs/cgroup
        - name: sys
          hostPath:
            path: /sys
        {{- if include "runc-root" . }}
        - name: runc-root
          hostPath:
            path: {{ include "runc-root-host-path" . }}
        {{- end }}
        {{- if or .Values.agent.openshift (.Capabilities.APIVersions.Has "apps.openshift.io/v1") }}
        - name: run-containers
          hostPath:
            path: /run/containers
        - name: var-lib-containers
          hostPath:
            path: /var/lib/containers
        - name: var-run
          hostPath:
            path: /var/run
        {{- end }}
{{- with .Values.agent.extraVolumes  }}
{{ toYaml . | indent 8 }}
{{- end }}
{{- end -}}