{{- if .Values.rbac.create -}}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "steadybit-agent.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "steadybit-agent.commonLabels" . | nindent 4 }}
  {{- range $key, $value := .Values.agent.extraLabels }}
    {{ $key }}: {{ $value }}
  {{- end }}
rules:
{{- if eq "leases" (include "validLeaderElection" .) }}
  - apiGroups: [ "coordination.k8s.io" ]
    resources:
      - "leases"
    verbs: [ "get", "list", "watch", "create", "update" ]
{{- end -}}
  {{- if eq "configmaps" (include "validLeaderElection" .) }}
  - apiGroups: [ "" ]
    resources:
      - "configmaps"
    verbs: [ "get", "list", "watch", "create", "update" ]
{{- end -}}
{{- end -}}