---
apiVersion: v1
kind: Secret
metadata:
  name: docker-steadybit-io
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "steadybit-agent.commonLabels" . | nindent 4 }}
  {{- range $key, $value := .Values.agent.extraLabels }}
    {{ $key }}: {{ $value }}
  {{- end }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecretDockerRegistry" . }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "steadybit-agent.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "steadybit-agent.commonLabels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.agent.key }}
  key: {{ .Values.agent.key | b64enc | quote }}
  {{- end }}