{{- if .Values.image.registry.password -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "steadybit-agent.fullname" . }}-pull-secrets
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "steadybit-agent.commonLabels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecretDockerRegistry" . }}
{{- end -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "steadybit-agent.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "steadybit-agent.commonLabels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.agent.key }}
  key: {{ .Values.agent.key | b64enc | quote }}
  {{- end }}