{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "steadybit-agent.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "steadybit-agent.commonLabels" . | nindent 4 }}
  {{- end }}
