apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- range $key, $value := .Values.extraLabels }}
    {{ $key }}: {{ $value }}
  {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.deployment.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.deployment.name }}
    spec:
      containers:
        - image: {{ .Values.image.name }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: steadybit-extension-crud
          resources:
            requests:
              memory: {{ .Values.resources.requests.memory }}
              cpu: {{ .Values.resources.requests.cpu }}
            limits:
              memory: {{ .Values.resources.limits.memory }}
              cpu: {{ .Values.resources.limits.cpu }}
          env:
            - name: STEADYBIT_EXTENSION_PORT
              value: "8080"
            - name: STEADYBIT_EXTENSION_INSTANCE_NAME
              value: {{ .Values.crud.instanceName | quote }}
            - name: STEADYBIT_EXTENSION_TARGET_TYPE
              value: {{ .Values.crud.targetType | quote }}
            - name: STEADYBIT_EXTENSION_TARGET_TYPE_LABEL
              value: {{ .Values.crud.targetTypeLabel | quote }}
            - name: STEADYBIT_LOG_LEVEL
              value: {{ .Values.logging.level | quote }}
            - name: STEADYBIT_LOG_FORMAT
              value: {{ .Values.logging.format | quote }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
      {{- toYaml . | nindent 8 }}
      {{- end }}