apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- range $key, $value := .Values.extraLabels }}
    {{ $key }}: {{ $value }}
  {{- end }}
  annotations:
    "steadybit.com/extension-auto-discovery": >
      {
        "extensions": [
          {
            "port": 8080,
            "types": ["ACTION", "DISCOVERY"]
          }
        ]
      }
spec:
  selector:
    app.kubernetes.io/name: {{ .Values.deployment.name }}
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
