apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "steadybit-platform.fullname" . }}
  labels:
    {{- include "steadybit-platform.commonLabels" . | nindent 4 }}
  {{- range $key, $value := .Values.platform.extraLabels }}
    {{ $key }}: {{ $value }}
  {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "steadybit-platform.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "steadybit-platform.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        - name: docker-steadybit-io
      serviceAccountName: {{ include "steadybit-platform.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.name }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: ui-port
              containerPort: 8080
              protocol: TCP
            - name: websocket-port
              containerPort: 7878
              protocol: TCP
          env:
            - name: STEADYBIT_TENANT_AGENTKEY
              value: {{ .Values.agent.key }}
            - name: SPRING_DATASOURCE_URL
              value: {{ .Values.platform.database.url }}
            - name: SPRING_DATASOURCE_USERNAME
              value: {{ .Values.platform.database.user }}
            - name: SPRING_DATASOURCE_PASSWORD
              value: {{ .Values.platform.database.password }}
            - name: STEADYBIT_TENANT_KEY
              value: {{ .Values.platform.tenant.key }}
            - name: STEADYBIT_TENANT_NAME
              value: {{ .Values.platform.tenant.name }}
            - name: STEADYBIT_WEB_PUBLIC_EXPERIMENT_PORT
              value: {{ .Values.platform.publicWebsocketPort }}
            {{- range $key, $value := .Values.platform.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
      {{- toYaml . | nindent 8 }}
      {{- end }}