apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "steadybit-platform.fullname" . }}
  labels:
    {{- include "steadybit-platform.commonLabels" . | nindent 4 }}
  {{- range $key, $value := .Values.platform.extraLabels }}
    {{ $key }}: {{ $value }}
  {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "steadybit-platform.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "steadybit-platform.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        - name: docker-steadybit-io
      serviceAccountName: {{ include "steadybit-platform.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.name }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: ui-port
              containerPort: 8080
              protocol: TCP
            - name: websocket-port
              containerPort: 7878
              protocol: TCP
          {{- if .Values.platform.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              port: ui-port
              path: /api/health/readiness
            initialDelaySeconds: {{ .Values.platform.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.platform.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.platform.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.platform.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.platform.readinessProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.platform.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              port: ui-port
              path: /api/health/liveness
            initialDelaySeconds: {{ .Values.platform.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.platform.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.platform.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.platform.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.platform.livenessProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.platform.startupProbe.enabled }}
          startupProbe:
            httpGet:
              port: ui-port
              path: /api/health
            initialDelaySeconds: {{ .Values.platform.startupProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.platform.startupProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.platform.startupProbe.timeoutSeconds }}
            successThreshold: {{ .Values.platform.startupProbe.successThreshold }}
            failureThreshold: {{ .Values.platform.startupProbe.failureThreshold }}
          {{- end }}
          env:
            - name: STEADYBIT_TENANT_AGENTKEY
              value: {{ .Values.agent.key | quote }}
            - name: SPRING_DATASOURCE_URL
              value: {{ .Values.platform.database.url | quote }}
            - name: SPRING_DATASOURCE_USERNAME
              value: {{ .Values.platform.database.user | quote }}
            - name: SPRING_DATASOURCE_PASSWORD
              value: {{ .Values.platform.database.password | quote }}
            - name: STEADYBIT_TENANT_KEY
              value: {{ .Values.platform.tenant.key | quote }}
            - name: STEADYBIT_TENANT_NAME
              value: {{ .Values.platform.tenant.name | quote }}
            - name: STEADYBIT_WEB_PUBLIC_EXPERIMENT_PORT
              value: {{ .Values.platform.publicWebsocketPort | quote }}
            {{- if .Values.platform.env }}
{{ toYaml .Values.platform.env | indent 12}}
            {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
      {{- toYaml . | nindent 8 }}
      {{- end }}