{{- if .Values.ingress.enabled -}}
  {{- $fullName := include "steadybit-platform.fullname" . -}}
  {{- $uiPort := .Values.platform.uiPort -}}
  {{- $websocketPort := .Values.platform.websocketPort -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "steadybit-platform.commonLabels" . | nindent 4 }}
  {{- range $key, $value := .Values.platform.extraLabels }}
    {{ $key }}: {{ $value }}
  {{- end }}
  {{- with .Values.ingress.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    {{- if .Values.ingress.hosts }}
    {{- range .Values.ingress.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          - pathType: Prefix
            path: /ws
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $websocketPort }}
          - pathType: Prefix
            path: /
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $uiPort }}
    {{- end }}
    {{- else }}
    - http:
        paths:
          - pathType: Prefix
            path: /ws
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $websocketPort }}
          - pathType: Prefix
            path: /
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $uiPort }}
  {{- end }}
{{- end }}
