---
apiVersion: v1
kind: Secret
metadata:
  name: docker-steadybit-io
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "steadybit-platform.commonLabels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecretDockerSteadybitIo" . }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "steadybit-platform.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "steadybit-platform.commonLabels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.agent.key }}
  key: {{ .Values.agent.key | b64enc | quote }}
  {{- end }}