name: Lint and Test Charts

on:
  push:
  pull_request:
    paths:
      - "charts/**"

jobs:
  lint-and-test-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.9.0

      - name: Add dependency chart repos
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami          
          helm repo add extension-aws https://steadybit.github.io/extension-aws
          helm repo add extension-datadog https://steadybit.github.io/extension-datadog
          helm repo add extension-http https://steadybit.github.io/extension-http
          helm repo add extension-istio https://steadybit.github.io/extension-istio
          helm repo add extension-kong https://steadybit.github.io/extension-kong
          helm repo add extension-kubernetes https://steadybit.github.io/extension-kubernetes
          helm repo add extension-postman https://steadybit.github.io/extension-postman
          helm repo add extension-prometheus https://steadybit.github.io/extension-prometheus
          helm repo add extension-prometheus https://steadybit.github.io/extension-host

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.4.0

      - name: Add unit testing plugin
        run: |
          helm plugin install https://github.com/quintush/helm-unittest

      - name: Run chart lint
        run: make chartlint

      - name: Run chart unit tests
        run: make charttesting