name: Lint and Test Charts

on:
  pull_request:
    paths:
      - "charts/**"

jobs:
  lint-and-test-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.9.0

      - name: Add dependency chart repos
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.2.1

      - name: Add unit testing plugin
        run: |
          helm plugin install https://github.com/quintush/helm-unittest

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch $GITHUB_BASE_REF)
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi
        env:
          GITHUB_BASE_REF: $github.base_ref

      - name: Run chart-testing (lint)
        run: ct lint --target-branch $GITHUB_BASE_REF --excluded-charts extensionlib
        env:
          GITHUB_BASE_REF: $github.base_ref

      - name: Run unit tests
        run: ./bin/run-unit_tests.sh