name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.9.0

      - name: Add dependency chart repos
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo add extension-aws https://steadybit.github.io/extension-aws
          helm repo add extension-datadog https://steadybit.github.io/extension-datadog
          helm repo add extension-http https://steadybit.github.io/extension-http
          helm repo add extension-istio https://steadybit.github.io/extension-istio
          helm repo add extension-kong https://steadybit.github.io/extension-kong
          helm repo add extension-kubernetes https://steadybit.github.io/extension-kubernetes
          helm repo add extension-postman https://steadybit.github.io/extension-postman
          helm repo add extension-prometheus https://steadybit.github.io/extension-prometheus
          helm repo add extension-host https://steadybit.github.io/extension-host

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.4.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
