apiVersion: apps/v1
kind: Deployment
metadata:
  name: steadybit-extension-datadog
  namespace: {{ .Release.Namespace }}
  labels:
  {{- range $key, $value := .Values.extraLabels }}
    {{ $key }}: {{ $value }}
  {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: steadybit-extension-datadog
  template:
    metadata:
      labels:
        app.kubernetes.io/name: steadybit-extension-datadog
    spec:
      containers:
        - image: {{ .Values.image.name }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: steadybit-extension-datadog
          ports:
            - containerPort: 8090
          resources:
            requests:
              memory: {{ .Values.resources.requests.memory }}
              cpu: {{ .Values.resources.requests.cpu }}
            limits:
              memory: {{ .Values.resources.limits.memory }}
              cpu: {{ .Values.resources.limits.cpu }}
          env:
            - name: STEADYBIT_LOG_LEVEL
              value: {{ .Values.logging.level | quote }}
            - name: STEADYBIT_EXTENSION_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "secret.name" . }}
                  key: apiKey
            - name: STEADYBIT_EXTENSION_APPLICATION_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "secret.name" . }}
                  key: applicationKey
            - name: STEADYBIT_EXTENSION_SITE_PARAMETER
              valueFrom:
                secretKeyRef:
                  name: {{ include "secret.name" . }}
                  key: siteParameter
            - name: STEADYBIT_EXTENSION_SITE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "secret.name" . }}
                  key: siteUrl
      {{- with .Values.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
      {{- toYaml . | nindent 8 }}
      {{- end }}