{{- if not .Values.datadog.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secret.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- range $key, $value := .Values.extraLabels }}
    {{ $key }}: {{ $value }}
  {{- end }}
type: Opaque
data:
  apiKey: {{ .Values.datadog.apiKey | b64enc | quote }}
  applicationKey: {{ .Values.datadog.applicationKey | b64enc | quote }}
  siteParameter: {{ .Values.datadog.siteParameter | b64enc | quote }}
  siteUrl: {{ .Values.datadog.siteUrl | b64enc | quote }}
{{- end }}