apiVersion: v1
kind: Service
metadata:
  name: steadybit-extension-datadog
  namespace: {{ .Release.Namespace }}
  labels:
  {{- range $key, $value := .Values.extraLabels }}
    {{ $key }}: {{ $value }}
  {{- end }}
  annotations:
    "steadybit.com/extension-auto-discovery": >
      {
        "extensions": [
          {
            "port": 8090,
            "types": ["action", "discovery", "event"],
            "tls": {
              {{- if .Values.tls.server.certificate.fromSecret }}
              "server": {
                "extraCertsFile": "/opt/steadybit/agent/etc/extension-mtls/{{ .Values.tls.server.certificate.fromSecret }}/tls.crt"
              {{ if .Values.tls.client.certificates.fromSecrets -}}
              },
              {{- else -}}
              }
              {{- end -}}
              {{- end }}
              {{ if .Values.tls.client.certificates.fromSecrets -}}
              "client": {
                "certChainFile": "/opt/steadybit/agent/etc/extension-mtls/{{ first .Values.tls.client.certificates.fromSecrets }}/tls.crt",
                "certKeyFile": "/opt/steadybit/agent/etc/extension-mtls/{{ first .Values.tls.client.certificates.fromSecrets }}/tls.key"
              }
              {{- end }}
            }
          }
        ]
      }
spec:
  selector:
    app.kubernetes.io/name: steadybit-extension-datadog
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
