apiVersion: v1
kind: Service
metadata:
  name: steadybit-extension-datadog
  namespace: {{ .Release.Namespace }}
  labels:
  {{- range $key, $value := .Values.extraLabels }}
    {{ $key }}: {{ $value }}
  {{- end }}
  annotations:
    "steadybit.com/extension-auto-discovery": >
      {
        "extensions": [
          {
            "port": 8090,
            "types": ["action", "discovery", "event"]
          }
        ]
      }
spec:
  selector:
    app.kubernetes.io/name: steadybit-extension-datadog
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
